<?php
   $products = $block->getFlashsaleProducts();
   $showWishlist = true;
   $showCompare = true;
   $showCart = true;
   $flashDetails = $block->getFlashsaleDetails();
   $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>

<div class="container">
    <div class="text-right">
        <div id="countdown">   
          <span><span id="days"></span></span>
          <span><span id="hours"></span></span>
          <span><span id="minutes"></span></span>
          <span><span id="seconds"></span></span>
      </div>
  </div>
    <div class="block-title">
        <h2 class="title"><?= $block->getFlashsaleProductsName() ?></h2>
    </div>
    <?php if (empty($products)): ?>
    <div class="message info empty">
        <div><?= /* @noEscape */ __('No Flash Sale Product Found.') ?></div>
    </div>
    <?php else: ?>
    <div class="products-grid grid">
        <ol class="product-items widget-product-grid">
            <div class="owl-carousel" id="flaseSale">
                <?php foreach ($products as $_product): ?>
                <?php $postParams = $block->getAddToCartPostParameters($_product); ?>
                <li class="product-item item">
                    <div class="product-item-info">
                        <?php 
                            $image = 'category_page_grid';
                            $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE);
                            $productImageUrl = $productImage->getUrl();
                        ?>
                        <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" class="product-item-photo">
                            <span class="product-image-container" style="width: 240px;">
                                <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <img class="product-image-photo" src="<?= $productImageUrl ?>" alt="flash-sale" width="300" height="300" /></span>
                            </span>
                        </a>
                        <div class="product-item-details">
                            <strong class="product-item-name">
                                <?= $block->escapeHtml('SKU  '.$_product->getSku()) ?>
                            </strong>
                            <?= /* @noEscape */ $block->getPrice($_product) ?>
                            <?php
                        if ($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
                                 echo $block->getProductDetailsHtml($_product);
                        } ?>
                        </div>
                    </div>
                </li>
                <?php endforeach ?>
            </div>
        </ol>
    </div>
</div>

<script>
    require(['jquery', 'owlcarousel'], function($) {
        $(document).ready(function() {
            $('#flaseSale').owlCarousel({
                loop: true,
                nav: false,
                dots: false,
                autoplay: true,
                autoplayHoverPause: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    600: {
                        items: 2
                    },
                    767: {
                        items: 3
                    },
                    1000: {
                        items: 4
                    },
                    1200: {
                        items: 5
                    },
                    1469: {
                        items: 6
                    }
                }
            });
        });
    });

</script>
<script type="text/javascript">(function () {
  const second = 1000,
        minute = second * 60,
        hour = minute * 60,
        day = hour * 24;
   let toDate = new Date('<?=$flashDetails['end_date'] ?>');
   let today = new Date(),
      dd = String(today.getDate()).padStart(2, "0"),
      mm = String(today.getMonth() + 1).padStart(2, "0"),
      yyyy = today.getFullYear(),
      end_date = new Date('<?=$flashDetails['end_date'] ?>');

  const countDown = new Date(end_date).getTime(),
      x = setInterval(function() {    

        const now = new Date().getTime(),
              distance = countDown - now;
        var tag = document.createElement("span");
         
        document.getElementById("days").innerText = Math.floor(distance / (day)),
          document.getElementById("hours").innerText = Math.floor((distance % (day)) / (hour)),
          document.getElementById("minutes").innerText = Math.floor((distance % (hour)) / (minute)),
          document.getElementById("seconds").innerText = Math.floor((distance % (minute)) / second);

        //do something later when date is reached
        if (distance < 0) {
          document.getElementById("countdown").style.display = "none";
          document.getElementById("content").style.display = "block";
          clearInterval(x);
        }
        //seconds
      }, 0)
  }());</script>
<?php endif; ?>
