<?php
$helper = $this->helper(\Elsnertech\Homeslider\Helper\Data::class);
$storeid = $helper->getStoreId();
?>

    <div id="homeSlider" class="slider slick-slider  banner web-banner">

        <?php
          $collection = $block->getResult();
          
        foreach ($collection as $item) {
            if ($storeid == $item['store_id'] || $item['store_id'] == 0):?>

        <div class="item">
            <div data-th="Image" class="image-slider">
                <img src="<?=/* @noEscape */ $block->getBaseUrl().$item->getData('image'); ?>" />
            </div>
            <div class="owl-content">
                <?=/* @noEscape */ $item->getData('image_text');?>
                <a href="<?=/* @noEscape */
                $block->getBaseLink().$item->getData('link'); ?>" class="banner-btn btn button-primary">
                   <span> <?=/* @noEscape */ __("Shop All");?> </span>
                </a>
            </div>
        </div>
        <?php endif;?>
        <?php } ?>

    </div>
<script data="js" type="text/javascript">
    
        $("#homeSlider").slick({
            margin: 0,
            nav: true,
            navText: ["<i class='porto-icon-chevron-left'></i>", "<i class='porto-icon-chevron-right'></i>"],
            dots: true,
            autoplay: false,
            autoplayTimeout: 4000,
            responsive: {
                0: {
                    items: 1
                },
                768: {
                    items: 1
                },
                992: {
                    items: 1
                },
                1200: {
                    items: 1
                }
            }
        });
    
</script>