<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
$helper = $this->helper('Elsnertech\Customisation\Helper\Data');
$mediaUrl = $helper->getMediaUrl();
$bannerImage = $helper->getConfig('login/mainConfig/banner_image');
$imageText = $helper->getConfig('login/mainConfig/login_content');
?>
<div class="inner-banner">
    <div class="banner-image">
        <img src="<?= $mediaUrl.'theme/'.$bannerImage;?>"/>
         <?= $imageText; ?>
    </div>
</div>