<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
$helper = $this->helper(\Elsnertech\Customisation\Helper\Data::class);
$mediaUrl = $helper->getMediaUrl();
$bannerImage = $helper->getConfig('login/mainConfig/banner_image');
$imageText = $helper->getConfig('login/mainConfig/login_content');
$regImageText = $helper->getConfig('login/mainConfig/reg_content');
?>
<div class="inner-banner">
    <div class="banner-image">
        <img src="<?=/* @noEscape */ $mediaUrl.'theme/'.$bannerImage;?>"/>
        <div class="login-breadcrums"> 
            <?=/* @noEscape */ $imageText; ?>
        </div>
        <div class="reg-breadcrums"  style="display:none;"> 
             <?=/* @noEscape */ $regImageText; ?>
        </div>
    </div>
</div>