<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit);
$elsnerHelper = $this->helper(\Elsnertech\Customisation\Helper\Data::class);
$storeUrl = $elsnerHelper->getBaseUrl();
?>

<nav class="navigation navigation sw-megamenu" data-action="navigation">
    <ul class="mobile-main-category desktophide">
        <li class="ui-menu-item home-catagory">
            <a href="<?= /* @noEscape */ $storeUrl;?>" class="level-top" title="บ้าน"><span><?=/* @noEscape */ __('Home');?></span></a>
        </li>
    </ul>
    <div class=" toggle-category desktophide" id="category">
        <a href="javascript:void(0)"><?= /* @noEscape */__('Category');?></a>
    </div>
    <ul class="slick-slider menu-slider" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
    <ul class="cms-page-link">
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'flash-sale';?>" class="level-top"
                title="<?=/* @noEscape */ __('Flash sales');?>"><?=/* @noEscape */ __('Flash sales');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'products/3/promotion.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('Promotions');?>"><?=/* @noEscape */ __('Promotions');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'mproduct/best-seller.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('Best Sellers');?>"><?=/* @noEscape */ __('Best Sellers');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'buy-payment/how-to-buy.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('How to order');?>"><?=/* @noEscape */ __('How to order');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'payment';?>" class="level-top"
                title="<?=/* @noEscape */ __('Payment method');?>"><?=/* @noEscape */ __('Payment method');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'condominium';?>" class="level-top"
                title="<?=/* @noEscape */ __('Furniture Set');?>"><?=/* @noEscape */ __('Furniture Set');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'lazada';?>" class="level-top"
                title="?=/* @noEscape */ __('Buy from other platform');?>"><?=/* @noEscape */ __('Buy from other platform');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'apartment';?>" class="level-top"
                title="บ้าน"><?=/* @noEscape */ __('Apartment');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'about-us';?>" class="level-top"
                title="<?= /* @noEscape */__('About Us');?>"><?= /* @noEscape */__('About Us');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'contact';?>" class="level-top"
                title="<?=/* @noEscape */ __('Contact Us');?>"><?=/* @noEscape */ __('Contact Us');?></a>
        </li>
    </ul>
    <div class="category-menu">
        <span class="down-arrow"></span>
        <div class="category-lists">
            <ul></ul>
        </div>
    </div>
</nav>
