<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php if ($crumbs && is_array($crumbs)): ?>
<div class="breadcumb-wrapper">
    <?php $lastCrums = end($crumbs);?>
    <h4><?= /* @noEscape */ __($lastCrums['label']);?></h4>
    <ul class="items">
        <?php foreach ($crumbs as $crumbName => $crumbInfo): ?>
            <li class="item <?= __($block->escapeHtmlAttr($crumbName)) ?>">
                <?php if ($crumbInfo['link']): ?>
                    <a href="<?= __($block->escapeUrl($crumbInfo['link'])); ?>"
                    title="<?=__($block->escapeHtml($crumbInfo['title'])); ?>" >
                        <?= __($block->escapeHtml($crumbInfo['label'])) ?>
                    </a>
                <?php endif; ?>
            <?php if ($crumbInfo['last']): ?>
                <strong><?= __($block->escapeHtml($crumbInfo['label'])) ?></strong>
            <?php endif; ?>
            </li>
            
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
