<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */

$columnsLimit = $block->getColumnsLimit() ?: 0;
$_menuHtml = $block->getHtml('level-top', 'submenu', $columnsLimit)
?>

<nav class="navigation navigation sw-megamenu" data-action="navigation">
    <ul class="slick-slider menu-slider-custom" data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @noEscape */ $_menuHtml?>
        <?= $block->getChildHtml() ?>
    </ul>
    <div class="category-menu">
        <span class="down-arrow" id="menuDesk"></span>
        <div class="category-lists" id="categoyList">
            <ul>
                  <?= /* @noEscape */ $_menuHtml?>
                <?= $block->getChildHtml() ?>
            </ul>
        </div>
    </div>
</nav>
