<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<div class="product details product-item-details">
<div class="product-sku">
     <span><?=/* @noEscape */ __('Sku');?> : </span
     ><span class="sku-number"><?= /* @noEscape */$product->getSku();?></span>
</div>
<strong class="product name product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>"
    title="<?= $block->escapeHtmlAttr($product->getName()) ?>"
    class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
</div>