<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="contact-form">
    <div class="block-title">
        <h2><?= __('Reach out to one excellent');?></h2>
    </div>
    <form class="form contact contactform"
        action="<?php echo $block->getFormAction(); ?>"
        id="contact-form"
        method="post"
        data-hasrequired="<?php echo __('* Required Fields') ?>"
        data-mage-init='{"validation":{}}'>
        
        <fieldset class="fieldset">
            <div class="fieldset row">
                <div class="fields col-md-12">
                <div class="field name required">
                    <label class="label" for="name"><span><?php echo __('Name') ?></span></label>
                    <div class="control">
                        <input name="name" id="name" title="<?php echo __('Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}" placeholder="Richard King"/>
                    </div>
                </div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php echo __('Email Address') ?></span></label>
                    <div class="control">
                        <input name="email" id="email" title="<?php echo __('Email Address') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}" placeholder="abc@abc.com"/>
                    </div>
                </div>
                <div class="field telephone">
                    <label class="label" for="telephone"><span><?php echo __('Phone Number') ?></span></label>
                    <div class="control">
                        <input name="telephone" id="telephone" title="<?php echo __('Phone Number') ?>" value="" class="input-text" type="text" placeholder="+91 657894561"/>
                    </div>
                </div>
                <div class="field comment required">
                    <label class="label" for="comment"><span><?php echo __('Message') ?></span></label>
                    <div class="control">
                        <textarea name="comment" id="comment" title="<?php echo __('Message') ?>" class="input-text" cols="5" rows="8" data-validate="{required:true}" placeholder="Hello there"></textarea>
                    </div>
                </div>
                <?php echo $block->getChildHtml('form.additional.info'); ?>
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?php echo __('Send Message') ?>" class="action submit button-primary">
                    <span><?php echo __('Send Message') ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
