<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\CategoryRenderer
 * @var $escaper \Magento\Framework\Escaper
 */
$attributeCode = $block->getAttributeCode();
$filterAccessor = $attributeCode . rand(100000, 1000000);
$lastLevel     = 0;
$filterItems   = $block->getFilterItems();
?>
<div data-mst-nav-filter="<?= /* @noEscape */$filterAccessor ?>" class="mst-nav__label mst-nav__category">
    <?= /* @noEscape */$block->getSearchBoxElement($filterAccessor) ?>

    <ol class="items">
        <?php foreach ($filterItems as $key => $filterItem):
            $label = $filterItem->getData('label');
            $numberOfResults = $filterItem->getData('count');
            $level = $filterItem->getData('level');
            $isParent = $filterItem->getData('is_parent');
        
            $isItemChecked = $block->isFilterItemChecked($filterItem, true);

            $cssClass = [
                'item',
                'mst-nav__label-item',
                '_mode-' . $block->getFilterItemDisplayMode('category_ids'),
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
                $isParent ? '_parent' : '',
            ];
            ?>

            <?=/* @noEscape */ $level > $lastLevel
            ? str_repeat('<ol class="items">', $level - $lastLevel)
            : str_repeat('</ol>', $lastLevel - $level)
            ?>

            <li data-element="filter" data-value="<?= /* @noEscape */$filterItem->getValueString() ?>"
            class="<?=/* @noEscape */ implode(' ', $cssClass) ?> sub-cat-filter">
                <?php if ($numberOfResults >= 0): ?>
                    <?php
                    $url = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
                    $id  = $block->getItemId($filterItem);
                    ?>
                    <a href="<?= /* @noEscape */$filterItem->getData('count') > 0 ? $escaper->escapeUrl($url) : '#' ?>"
                    rel="<?=/* @noEscape */ $block->getRelAttributeValue() ?>">
                        <input id="<?=/* @noEscape */ $id ?>" type="checkbox" <?= $isItemChecked ? 'checked' : '' ?>
                            <?= $filterItem->getData('count') == 0 ? 'disabled' : '' ?> />

                        <label for="<?= /* @noEscape */$id ?>">
                            <span><?= /* @noEscape */$label ?></span>
                            <?= /* @noEscape */$block->getCountElement($filterItem) ?>
                        </label>
                    </a>
                <?php else: ?>
                    <span><?=/* @noEscape */ $label ?></span>
                    <?=/* @noEscape */ $block->getCountElement($filterItem) ?>
                <?php endif ?>
            </li>
            <?php $lastLevel = $level ?>
        <?php endforeach ?>

        <?=/* @noEscape */ $block->getSizeLimiterElement($filterAccessor) ?>
    </ol>
</div>
<script type="text/x-magento-init"><?= \Zend_Json::encode([
        '[data-mst-nav-filter=' . $filterAccessor . ']' => [
            'Mirasvit_LayeredNavigation/js/renderer/label-renderer' => [],
        ],
    ]) ?></script>


