<?php
/**
 * @var $block \Mirasvit\LayeredNavigation\Block\Renderer\LabelRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

$attributeCode  = $block->getAttributeCode();
$cacheKey       = rand(100000, 1000000);
$filterAccessor = $attributeCode . 'A' . $cacheKey . 'A';
?>
<div data-mst-nav-filter="<?=/* @noEscape */ $filterAccessor ?>"
class="mst-nav__label" data-mst-nav-cache-key="<?= /* @noEscape */$cacheKey ?>">
    <?=/* @noEscape */ $block->getSearchBoxElement($filterAccessor) ?>

    <ol class="items">
        <?php foreach ($block->getFilterItems() as $key => $filterItem):
            $label = $filterItem->getData('label');
            $numberOfResults = $filterItem->getData('count');

            $isItemChecked = $block->isFilterItemChecked($filterItem, true);

            $imageUrl         = $block->getImageUrl($filterItem);
            $isFullWidthImage = $block->isFullWidthImage($filterItem);

            $cssClass = [
                'item',
                'mst-nav__label-item',
                '_mode-' . $block->getFilterItemDisplayMode($attributeCode),
                $isItemChecked ? '_checked' : '',
                $isItemChecked && $block->isHighlightEnabled() ? '_highlight' : '',
                $imageUrl ? '_image' : '',
                $imageUrl && $isFullWidthImage ? '_full-width' : '',
            ];
            ?>
             <?php if ($numberOfResults > 0): ?>
            <li data-element="filter"
            class="<?=/* @noEscape */ implode(' ', $cssClass) ?>price-filter-custom"
            data-value="<?= /* @noEscape */$filterItem->getValueString() ?>">
                    <?php if ($numberOfResults >= 0): ?>
                        <?php
                        $url = $isItemChecked ? $filterItem->getRemoveUrl() : $filterItem->getUrl();
                        $id  = $block->getItemId($filterItem);
                        ?>
                    <a href="<?= $escaper->escapeUrl($url) ?>"
                    rel="<?=/* @noEscape */ $block->getRelAttributeValue() ?>">
                        <?php if ($imageUrl): ?>
                            <div class="swatch-option image"
                            style="background: url(<?= /* @noEscape */$imageUrl ?>)
                            no-repeat center;  background-size: auto 100%;"></div>
                        <?php endif ?>

                        

                        <label for="<?=/* @noEscape */ $id ?>">
                            <?=/* @noEscape */ $label ?>
                        </label>
                        <div class="count-wrap">
                            <input id="<?=/* @noEscape */ $id ?>"
                            type="checkbox" <?= $isItemChecked ? 'checked' : '' ?> />
                            <?= /* @noEscape */$block->getCountElement($filterItem) ?>
                        </div>
                    </a>
                <?php else: ?>
                    <?= /* @noEscape */$label ?>
                    <?=/* @noEscape */ $block->getCountElement($filterItem) ?>
                <?php endif ?>
            </li>
            <?php endif ?>
        <?php endforeach ?>

        <?=/* @noEscape */ $block->getSizeLimiterElement($filterAccessor) ?>
    </ol>
</div>
<script type="text/x-magento-init"><?= \Zend_Json::encode([
        '[data-mst-nav-filter=' . $filterAccessor . ']' => [
            'Mirasvit_LayeredNavigation/js/renderer/label-renderer' => [],
        ],
    ]) ?></script>


