<?php
$socialfeeds = $block->helper(\Smartwave\Socialfeeds\Helper\Data::class);

$fb_result = $socialfeeds->getFBFans();
if ($fb_result): ?>
    <?php
    $fb_fans = $fb_result['fans'];
    ?>


<div class="block block-facebook-like">
    <div class="block-title">
        <strong>
            <span><?=/* @noEscape */ __('Facebook') ?></span>
            <a target="_blank" href="<?= /* @noEscape */ $fb_result['link'] ?>" class="btn-like f-right">
                <?= /* @noEscape */ __('Like!') ?>
            </a>
        </strong>
    </div>

    <div class="block-content">
        <div class="clearfix fb-persons">
            <?= /* @noEscape */ $fb_fans ?>
        </div>
    </div>
</div>
<?php endif; ?>