<?php
    $footer = $this->getConfig('porto_settings/footer');
    $helper = $this->helper(\Elsnertech\Customisation\Helper\Data::class);
   $mediaUrl = $helper->getMediaUrl();
   $storeUrl = $helper->getBaseUrl();
?>
<div class="footer">

    <div class="footer-middle">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12 ">
                    <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
                        <div class="widget contact-info">
                            <h3 class="widget-title"><?=/* @noEscape */ __('contact list') ?></h3>
                            <div class="contact-info contact-info-block">
                                <ul class="contact-details">
                                    <li>
                                        <span><?=/* @noEscape */ __('1364-68 Sukhumvit Road') ?>,
                                        <?=/* @noEscape */ __('Near Soi 76 (same side as Imperial Samrong)') ?>,
                                            <?=/* @noEscape */ __('Samut Prakan Province 10270') ?>,
                                            <?=/* @noEscape */ __('Thailand') ?>.</span>
                                    </li>

                                    <li><b class='tel-no'><?=/* @noEscape */ __('Tel: 02-7455981, 02-7455982') ?></b>
                                    <b class='fax-no'><?= /* @noEscape */__('Fax: 02-7455598') ?></b></li>
                                    <li>
                                        <div class="map-footer">
                                            <iframe width="300px" height="200px" frameborder="0"
                                            scrolling="no" marginheight="0" marginwidth="0" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3877.0609886233647!2d100.59635631425046!3d13.654053990410771!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30e2a0684869ecf1%3A0xc95245ee6a817f15!2z4Lir4LiZ4Li24LmI4LiH4LiU4Li14LmA4Lil4Li04LioIOC5gOC4n-C4reC4o-C5jOC4meC4tOC5gOC4iOC4reC4o-C5jA!5e0!3m2!1sen!2sin!4v1661505634642!5m2!1sen!2sin" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                                        </div>
                                    </li>
                                </ul>
                                <div class="desktop-hide-cont">
                                    <h3 class="widget-title"><?=/* @noEscape */ __('Hotline') ?></h3>
                                    <div class="footer-call">
                                        <a href="tel:086-600-4332"> 086-600-4332 </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-2 col-md-4 col-sm-4 col-6">
                    <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
                        <div class="widget_text widget widget_custom_html">
                            <h3 class="widget-title"><?=/* @noEscape */ __('HELP') ?></h3>
                            <div class="textwidget custom-html-widget">
                                <ul>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'built-in.html';?>">
                                    <?=/* @noEscape */ __('Interior') ?></a></li>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'blog.html';?>">
                                    <?=/* @noEscape */ __('Article') ?></a></li>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'apartment.html';?>">
                                    <?= /* @noEscape */__('Apartment') ?></a></li>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'condominium.html';?>">
                                    <?=/* @noEscape */ __('Condominium') ?></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                    <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
                        <div class="widget_text widget widget_custom_html">
                            <h3 class="widget-title"><?= /* @noEscape */__('website menu') ?></h3>
                            <div class="textwidget custom-html-widget">
                                <ul>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'lazada.html';?>">
                                    <?=/* @noEscape */ __('Lazada Shopee') ?></a></li>
                                    <li><a href="<?= /* @noEscape */$storeUrl.'taxinvoice';?>">
                                    <?=/* @noEscape */ __('Tax invoice') ?></a></li>
                                    <li><a href="<?= /* @noEscape */$storeUrl.'pay-slip.html';?>">
                                    <?=/* @noEscape */__('Payment invoice') ?></a></li>
                                    <li><a href="<?=/* @noEscape */ $storeUrl.'term-and-condition.html';?>">
                                    <?=/* @noEscape */ __('Order Cancellation and Return Policy') ?></a></li>
                                    <li><a href="<?= /* @noEscape */$storeUrl.'latest-products.html';?>">
                                    <?=/* @noEscape */ __('Latest product') ?></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-3 col-md-4 col-sm-4">
                    <div data-content-type="html" data-appearance="default" data-element="main" data-decoded="true">
                        <div class="row">
                            <div>
                                <div class="column-inner">
                                    <div class="desktop-call">
                                        <h3 class="widget-title"><?=/* @noEscape */ __('HOTLINE') ?></h3>
                                        <div class="footer-call">
                                            <a href="tel:086-600-4332"> 086-600-4332 </a>
                                        </div>
                                    </div>
                                    <div class="footer-line">
                                        <span>
                                            <?=/* @noEscape */ __('Line ID:') ?>
                                        </span>
                                        <a href="Https://line.me/R/ti/p/%40nrb3227f" target="_blank">@ 1deelert</a>
                                    </div>
                                    <div class="social-link">
                                        <a href="https://www.facebook.com/1deelert/" rel="nofollow" target="_blank" title="Facebook"
                                        class="social-footer">
                                            <img src="<?= /* @noEscape */$mediaUrl.'theme/icon-fb.png'?>"
                                            alt="footer" width="29" height="29">
                                        </a>
                                        <a href="" rel="nofollow" target="_blank" title="Instagram"
                                        class="social-footer" alt="footer" width="300" height="300">
                                            <img src="<?=/* @noEscape */ $mediaUrl.'theme/icon-insta.png'?>"
                                            alt="footer" width="29" height="29">
                                        </a>
                                        <a href="https://line.me/R/ti/p/%40nrb3227f" rel="nofollow" target="_blank" title="Line" class="social-footer">
                                            <img src="<?=/* @noEscape */ $mediaUrl.'theme/icon-link.png'?>"
                                            alt="footer" width="29" height="29">
                                        </a>
                                    </div>
                                    <div class="widget ">
                                        <picture>
                                           <a 
                                           href="https://www.trustmarkthai.com/callbackData/popup.php?data=0c89201
                                           d6-33-5-6f174ba41a7470b2c477a55516460c654272&markID=firstmar"
                                           target="_blank">
                                               <img src="<?=/* @noEscape */ $mediaUrl.'theme/footer-1.png'?>"
                                               alt="footer" width="230" height="48">
                                            </a>
                                        </picture>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="footer-last">
                <img class="desktop-imagelast" src="<?=/* @noEscape */ $mediaUrl.'theme/footer-bottom.png'?>"
                alt="footer" width="915" height="74">
                <img class="mobile-imagelast" src="<?=/* @noEscape */ $mediaUrl.'theme/footer-mb.png'?>"
                alt="footer" width="915" height="74">
            </div>
        </div>
        <div class="footer-bottom">
            <div class="container">

                <div class="custom-block f-left"><span>Nueng deelert</span></div>

                <div class="custom-block f-center">
                    <span>
                        <a href="<?=/* @noEscape */ $storeUrl.'term-and-condition';?>">Privacy Policy | Terms of use</a>
                    </span>
                </div>

                <div class="custom-block f-right">
                    <address><?=/* @noEscape */ $footer['footer_bottom_copyrights'] ?></address>
                </div>

            </div>
        </div>


    </div>
</div>
<div class="social-chat-icons">
    <div class="social-chat">
        <span class="help-btn"><?= /* @noEscape */__('Need help?');?></span>
    </div>
    <ul class="footer-social-icon">
        <li><a href="https://line.me/R/ti/p/%40nrb3227f" rel="nofollow" target="_blank"
        title="Line" class="share-Line">
        <img src="<?= /* @noEscape */$mediaUrl.'theme/default/Icon_awesome-line.png'?>"
        alt="footer" width="80" height="80" /></a></li>
        <li><a href="https://www.facebook.com/1deelert/" rel="nofollow" target="_blank"
        title="Facebook" class="share-facebook">
        <img src="<?=/* @noEscape */ $mediaUrl.'theme/default/Icon_awesome-facebook-messenger.png'?>"
        alt="footer" width="80" height="80" /></a></li>
        <li><a href="tel:086-600-4332" rel="nofollow" target="_blank"
        title="Phone" class="share-instagram">
        <img src="<?= /* @noEscape */$mediaUrl.'theme/default/Icon_zocial-call.png'?>"
        alt="footer" width="80" height="80" /></a></li>
    </ul>
</div>

<a href="javascript:void(0)" id="totop"><em class="porto-icon-up-open"></em></a>

