<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
/*Where there is only one option left in the dropdowns, autoselect it.*/
/*require(['jquery'], function($){ 
    $('select[id^="attribute"]').change(function(){
        var picked = this;
        setTimeout(function() {
                autoselect(picked,this.value);  //do the autoselect after everything else.
        }, 100);

    });
    function autoselect(picked,selectVal){
        var nextsel = $(picked).parent().parent().next().find('select[id^="attribute"]');
        // console.log($(nextsel).children().val());
        nextSalVal = $(nextsel).children().val();
        if($(nextsel).children().length > 0){
            $(nextsel).find(':nth-child(2)', picked).prop('selected',true);
            $(nextsel).change();
        };
    };
});*/
</script>
<?= $block->getChildHtml() ?>
