<?php if($block->isAllow()):?>
	<?php $block->getManifestFile();?>
<link rel="manifest" href="<?= $block->getCurrentStoreUrl()."manifest.json"?>">
<meta name="theme-color" content="<?= $block->getThemeColor()?>">
<link rel="apple-touch-icon" sizes="192x192" href="<?= $block->getIconUrl()?>">
<link rel="apple-touch-icon" sizes="512x512" href="<?= $block->getIconUrl()?>">
<script type="text/javascript">
	if ('serviceWorker' in navigator) {
	  window.addEventListener('load', function() {
		navigator.serviceWorker.register("<?= $block->getCurrentStoreUrl().'superpwa-sw.js'?>")
		.then(function(registration) { console.log('SuperPWA service worker ready'); registration.update(); })
		.catch(function(error) { console.log('Registration failed with ' + error); });
	  });
	}
</script>
<?php endif;?>