<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper(\Smartwave\Megamenu\Helper\Data::class);
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
    $header_type = $_helper->getConfig('porto_settings/header/header_type');

if ($_config['general']['enable']) {
    ?>
    <?php //$_menu = $block->getMegamenuHtml();
        $columnsLimit = $block->getColumnsLimit() ?: 0;
        $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit);
     ?>

<nav class="navigation sw-megamenu
    <?php if ($header_type == 7 ||
    $header_type == 8 ||
    $header_type == 18 ||
    $header_type == 22): ?>side-megamenu<?php endif; ?>"
role="navigation">
    <ul class="slick-slider menu-slider-custom">
        <?=/* @noEscape */ $_menu; ?>
    </ul>
    <div class="category-menu">
        <span class="down-arrow"></span>
        <div class="category-lists">
            <ul>
                <?=/* @noEscape */ $_menu; ?>
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
    });
</script>
    <?php
} else {
    ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?=/* @noEscape */ $_menu; ?>
    </ul>
</nav>

    <?php
}
?>
