<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper(\Smartwave\Megamenu\Helper\Data::class);
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
    $header_type = $_helper->getConfig('porto_settings/header/header_type');
    $elsnerHelper = $this->helper(\Elsnertech\Customisation\Helper\Data::class);
    $storeUrl = $elsnerHelper->getBaseUrl();

if ($_config['general']['enable']) {
    ?>
    <?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sw-megamenu
    <?php if ($header_type == 7 ||
    $header_type == 8 ||
    $header_type == 18 ||
    $header_type == 22): ?>side-megamenu<?php endif; ?>"
    role="navigation">
    
    <ul class="mobile-main-category desktophide">
        <li class="ui-menu-item home-catagory">
            <a href="<?= /* @noEscape */ $storeUrl;?>" class="level-top" title="บ้าน"><span><?=/* @noEscape */ __('Home');?></span></a>
        </li>
    </ul>
    <div class=" toggle-category desktophide" id="category">
        <a href="javascript:void(0)"><?= /* @noEscape */__('Category');?></a>
    </div>
    
    <ul class="slick-slider menu-slider">
        <?=/* @noEscape */ $_menu; ?>
    </ul>
  <!--   <div class="desktophide toggle-category" id="custMenu">
        <a href="javascript:void(0)"><?= /* @noEscape */__('Menu');?></a>
    </div> -->
    <ul class="cms-page-link">
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'flash-sale';?>" class="level-top"
                title="<?=/* @noEscape */ __('Flash sales');?>"><?=/* @noEscape */ __('Flash sales');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'products/3/promotion.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('Promotions');?>"><?=/* @noEscape */ __('Promotions');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'mproduct/best-seller.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('Best Sellers');?>"><?=/* @noEscape */ __('Best Sellers');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'buy-payment/how-to-buy.html';?>" class="level-top"
                title="<?=/* @noEscape */ __('How to order');?>"><?=/* @noEscape */ __('How to order');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'payment';?>" class="level-top"
                title="<?=/* @noEscape */ __('Payment method');?>"><?=/* @noEscape */ __('Payment method');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'condominium';?>" class="level-top"
                title="<?=/* @noEscape */ __('Furniture Set');?>"><?=/* @noEscape */ __('Furniture Set');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'lazada';?>" class="level-top"
                title="?=/* @noEscape */ __('Buy from other platform');?>"><?=/* @noEscape */ __('Buy from other platform');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'apartment';?>" class="level-top"
                title="บ้าน"><?=/* @noEscape */ __('Apartment');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?=/* @noEscape */ $storeUrl.'about-us';?>" class="level-top"
                title="<?= /* @noEscape */__('About Us');?>"><?= /* @noEscape */__('About Us');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= /* @noEscape */$storeUrl.'contact';?>" class="level-top"
                title="<?=/* @noEscape */ __('Contact Us');?>"><?=/* @noEscape */ __('Contact Us');?></a>
        </li>
    </ul>
    <div class="category-menu">
        <span class="down-arrow"></span>
        <div class="category-lists">
            <ul>
                <?=/* @noEscape */ $_menu; ?>
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
    });
</script>
    <?php
} else {
    ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?=/* @noEscape */ $_menu; ?>
    </ul>
</nav>

    <?php
}
?>
