<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper(\Smartwave\Megamenu\Helper\Data::class);
    $_config = $_helper->getConfig('sw_megamenu');
    $columnsLimit = 0;
    $header_type = $_helper->getConfig('porto_settings/header/header_type');
    $elsnerHelper = $this->helper('Elsnertech\Customisation\Helper\Data');
    $storeUrl = $elsnerHelper->getBaseUrl();

if ($_config['general']['enable']) {
    ?>
    <?php $_menu = $block->getMegamenuHtml(); ?>

<nav class="navigation sw-megamenu
    <?php if ($header_type == 7 ||
    $header_type == 8 ||
    $header_type == 18 ||
    $header_type == 22): ?>side-megamenu<?php endif; ?>"
    role="navigation">
    
    <ul class="mobile-main-category desktophide">
        <li class="ui-menu-item home-catagory">
            <a href="#" class="level-top" title="บ้าน"><span><?= __('Home');?></span></a>
        </li>
    </ul>
    <div class="toggle-category desktophide">
        <a href="javascript:void(0)"><?= /* @noEscape */__('Category');?></a>
    </div>
    
    <ul class="slick-slider menu-slider">
        <?=/* @noEscape */ $_menu; ?>
    </ul>
    <div class="cms-page-link">
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'flash-sale';?>" class="level-top" title="บ้าน"><?= __('Flash Sales');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'promotion';?>" class="level-top" title="บ้าน"><?= __('Promotions');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'latest-product';?>" class="level-top" title="บ้าน"><?= __('Best Sellers');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'how-to-buy';?>" class="level-top" title="บ้าน"><?= __('How To Buy');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'payment-method';?>" class="level-top" title="บ้าน"><?= __('Payment Option');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'condominium';?>" class="level-top" title="บ้าน"><?= __('Furniture Set');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'lazada';?>" class="level-top" title="บ้าน"><?= __('Buy from other platform');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'apartment';?>" class="level-top" title="บ้าน"><?= __('Apartment');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'about-us';?>" class="level-top" title="บ้าน"><?= __('About Us');?></a>
        </li>
        <li class="ui-menu-item cms-catagory">
                <a href="<?= $storeUrl.'contact';?>" class="level-top" title="บ้าน"><?= __('Contact Us');?></a>
        </li>
    </div>
    <div class="category-menu">
        <span class="down-arrow"></span>
        <div class="category-lists">
            <ul>
                <?=/* @noEscape */ $_menu; ?>
            </ul>
        </div>
    </div>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
    });
</script>
    <?php
} else {
    ?>
    <?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?=/* @noEscape */ $_menu; ?>
    </ul>
</nav>

    <?php
}
?>
