<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */
$schema = ($block->getZone() == 'item_view') ? true : false;
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
/** @var \Magento\Catalog\Pricing\Price\ConfiguredPrice $configuredPrice */
$configuredPrice = $block->getPrice();
/** @var \Magento\Catalog\Pricing\Price\ConfiguredRegularPrice $configuredRegularPrice */
$configuredRegularPrice = $block->getPriceType(
    \Magento\Catalog\Pricing\Price\ConfiguredPriceInterface::CONFIGURED_REGULAR_PRICE_CODE
);
$currecyHelper = $block->helper(\Elsnertech\Customisation\Helper\Data::class);
?>
<?php if ($configuredPrice->getAmount()->getValue() < $configuredRegularPrice->getAmount()->getValue()): ?>
        <div class="price-spacial-wrap">
                <span class="price-wrap">
                    <span class="currecny-symbol">
                        <?=/* @noEscape */ $currecyHelper->getCurrentCurrencySymbol();?>
                    </span>
                    <span class="product-price-new">
                        <?=/* @noEscape */ $configuredPrice->getAmount().'.00'; ?>
                    </span>
                </span>
                <span class="old-price-wrap">
                    <span class="currecny-symbol">
                        <?=/* @noEscape */ $currecyHelper->getCurrentCurrencySymbol();?>
                    </span>
                    <span class="product-price-old" id="old-price-2">
                        <?=/* @noEscape */ $configuredRegularPrice->getAmount().'.00' ;?>
                    </span>
                </span>
            </div>
<?php else: ?>
    <?php
    $priceLabel = ($block->getPriceLabel() !== null)
        ? $block->getPriceLabel()
        : '';
    ?>
    <span class="price-wrap">
        <span class="currecny-symbol"><?=/* @noEscape */$currecyHelper->getCurrentCurrencySymbol();?></span>
        <span class="product-price"><?=/* @noEscape */$configuredPrice->getAmount().'.00' ?></span>
    </span> 
<?php endif; ?>
