<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Generic.WhiteSpace.ScopeIndent.Incorrect

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$columns = "columns4";
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$review_model = $_portohelper->getModel('\Magento\Review\Model\Review');
$_category_config = $_portohelper->getConfig('porto_settings/category');
$currecyHelper = $this->helper('Elsnertech\Customisation\Helper\Data');
$_category_grid_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category_grid');
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;
            $upsell_columns = $_portohelper->getConfig('porto_settings/product/upsell_columns');
            if($upsell_columns)
                $columns = "";
            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();
            $columns = "columns4";

            $showWishlist = true;
            $showCompare = false;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}

$image = 'category_page_grid';
$hover_image = 'category_page_grid-hover';
$image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
$image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
?>

<?php if ($exist) :?>
<div class="related-product-wrap">
<div class="block <?= $block->escapeHtmlAttr($class) ?> latest-product-section ">
        <div class="related-products latest-product-block">
            <div class="container">
                <div class="block-title">
                    <h2 id="block-<?= $block->escapeHtmlAttr($class) ?>-heading" role="heading" aria-level="2"><?= __('Related Product');?></h2>
                </div>
                <div class="block-content">
                    <div class="slider-wrapper">
                        <div class="products wrapper grid products-grid   ">
                            <div class="filterproducts products products-slider list items product-items slider slick-slider relate-product-slick">
                                <?php foreach ($items as $_item): ?>
                                    <div class="item product product-item">                
                                        <div class="product-item-info">
                                            <div class="product photo product-item-photo">
                                            <a href="<?php echo $_item->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                                <?php
                                                    if($type == 'related') {
                                                        $_category_config['aspect_ratio'] = 0;
                                                        $image_width = 300;
                                                        $image_height = 300;
                                                    }
                                                    if($_category_config['aspect_ratio'])
                                                        $productImage = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                                    else
                                                        $productImage = $_imagehelper->init($_item, $image)->resize($image_width, $image_height);
                                                    $productImageUrl = $productImage->getUrl();
                                                ?>
                                                    <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>" alt=""/>
                                                <?php if($_category_config['alternative_image']): ?>
                                                <?php
                                                    if($_category_config['aspect_ratio'])
                                                        $productHoverImage = $_imagehelper->init($_item, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                                    else
                                                        $productHoverImage = $_imagehelper->init($_item, $hover_image)->resize($image_width, $image_height);
                                                    $productHoverImageUrl = $productHoverImage->getUrl();
                                                ?>
                                                    <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                                                    <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>" alt=""/>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            </a>
                                            </div>
                                            <div class="product details product-item-details">
                                                <strong class="product name product-item-name">
                                                    <?= 'SKU  '. $block->escapeHtml($_item->getSKU()) ?>
                                                </strong>
                                                <?php if($_item->getSpecialPrice()):?>
                                                    <div class="price-spacial-wrap">
                                                        <span class="price-wrap">
                                                            <span class="currecny-symbol"><?php echo $currecyHelper->getCurrentCurrencySymbol();?></span>
                                                            <span class="product-price-new"><?= number_format($_item->getSpecialPrice(), 2, ".", "") ?></span>
                                                        </span>
                                                        <span class="old-price-wrap">
                                                            <span class="currecny-symbol"><?php echo $currecyHelper->getCurrentCurrencySymbol();?></span>
                                                            <span class="product-price-old" id="old-price-2"><?= number_format($_item->getPrice(), 2, ".", "") ?></span>
                                                        </span>
                                                    </div>
                                                    <?php else:?>
                                                        <span class="price-wrap">
                                                            <span class="currecny-symbol"><?php echo $currecyHelper->getCurrentCurrencySymbol();?></span>
                                                            <span class="product-price"><?= number_format($_item->getFinalPrice(), 2, ".", "") ?></span>
                                                        </span>        
                                                    <?php endif;?>
                                            </div>
                                        </div>
                                    </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
<a href="javascript:void(0);" class="show-more"><?= __('Show more');?></a>
</div>
<?php endif; ?>

