<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>


<?php
    $helper = $this->helper(\Elsnertech\Wishlist\Helper\Data::class);
    $product = $block->getProduct();
?>

<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>

<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
<script>
require(['jquery', 'jquery/ui'], function($){
    $(document).ready(function() { 
            var checkClass = <?= $helper->getProductCollectionFromCategory($product->getId());?>;
            console.log(checkClass);
            if(checkClass){
                $('.action.towishlist').addClass('added');
            }
        });
    });
</script>
