<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>


<?php $product = $block->getProduct(); 
    $currecyHelper = $this->helper('Elsnertech\Customisation\Helper\Data');
?>

<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist <?= $product->getId()?>wishlistProduct"
       data-post='<?= /* @noEscape */ $block->getWishlistParams() ?>'
       data-action="add-to-wishlist"><span><?= $block->escapeHtml(__('Add to Wish List')) ?></span></a>

<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= /* @noEscape */ $block->getWishlistOptionsJson() ?>
        }
    }
</script>
<script type="text/javascript">
    require(["jquery"],function($) {
        $(document).ready(function() {
            var customurl = "<?php echo $currecyHelper->getBaseUrl().'wishlistclassadd/index/wishlistclass'?>";
            var param = 'ajax=1';
            $.ajax({
                showLoader: true,
                url: customurl,
                data: param,
                type: "POST",
                dataType: 'json'
            }).done(function (data) {
                console.log(data);
                $(data).each(function(index, value){
                    $('.'+value+'wishlistProduct').addClass('added');
                });
            });
        });
    });
</script>
