<?php $_product = $block->getProduct();?>
<div class="product-share">
  <div class="share-links">
    <a href="https://www.facebook.com/sharer.php?u=<?=/* @noEscape */ $_product->getProductUrl();?>"
    target="_blank"
    rel="nofollow"
    data-tooltip=""
    data-placement="bottom"
    title=""
    class="share-facebook"
    data-original-title="Facebook">Facebook</a>
        <a href="https://twitter.com/intent/tweet?text=<?= /* @noEscape */ $_product->getName();?>&amp;
        url=<?= /* @noEscape */ $_product->getProductUrl();?>"
        target="_blank"
        rel="nofollow"
        data-tooltip=""
        data-placement="bottom"
        title=""
        class="share-twitter"
        data-original-title="Twitter">Twitter</a>
    </div>
</div>
