<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
$_product = $block->getProduct();
$attribute = $_product->getResource()->getAttribute('warranty');
$weight= $_product->getResource()->getAttribute('weight')->getFrontend()->getValue($_product);
$warranty = $attribute->getFrontend()->getValue($_product);
$dimension=$_product->getResource()->getAttribute('dimension')->getFrontend()->getValue($_product);

if ($weight != '' || $warranty != '' || $dimension != ''): ?>
    <div class="product-attribute">
    <?php if ($weight != ''):?>
        <p class="product-category">
            <span class="attr-label">Weight:</span>
            <span><?= /* @noEscape */ $_product->getResource()
            ->getAttribute('weight')
            ->getFrontend()
            ->getValue($_product);?></span>
        </p>
    <?php endif;?>
    <?php if ($dimension != ''):?>
        <p class="product-category">
            <span class="attr-label">Dimension:</span>
            <span><?=/* @noEscape */ $_product->getResource()
            ->getAttribute('dimension')
            ->getFrontend()
            ->getValue($_product);?></span>
        </p>
    <?php endif;?>
    <?php if ($warranty != ''):?>
        <p class="product-category">
            <span class="attr-label">Warranty:</span>
            <span><?= /* @noEscape */ $attribute->getFrontend()->getValue($_product);?></span>
        </p>
    <?php endif;?>
   
    </div>
<?php endif;?>