<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\View
 */
$_product = $block->getProduct();
$attribute = $_product->getResource()->getAttribute('warranty');
?>
<div class="product-attribute">
<?php if($_product->getResource()->getAttribute('weight')->getFrontend()->getValue($_product) != ''):?>
    <p>
        <span class="attr-label">Weight:</span>
        <span><?=  $_product->getResource()->getAttribute('weight')->getFrontend()->getValue($_product);?></span>
    </p>
<?php endif;?>
<?php if($attribute->getFrontend()->getValue($_product) != ''):?>
    <p>
        <span class="attr-label">Warranty:</span>
        <span><?= $attribute->getFrontend()->getValue($_product);?></span>
    </p>
<?php endif;?>
<?php if($_product->getResource()->getAttribute('dimension')->getFrontend()->getValue($_product) != ''):?>
    <p>
        <span class="attr-label">Dimension:</span>
        <span><?= $_product->getResource()->getAttribute('dimension')->getFrontend()->getValue($_product);?></span>
    </p>
<?php endif;?>
</div>